CREATE TABLE STUDENT
(
  StudentID INT NOT NULL,
  StudentFName INT NOT NULL,
  StudentLName INT NOT NULL,
  PRIMARY KEY (StudentID)
);

CREATE TABLE INSTRUCTOR
(
  Inst.ID INT NOT NULL,
  Inst.FName INT NOT NULL,
  Inst.LName INT NOT NULL,
  PRIMARY KEY (Inst.ID)
);

CREATE TABLE CLASSE
(
  ClassID INT NOT NULL,
  Class_Type INT NOT NULL,
  Inst.ID INT NOT NULL,
  PRIMARY KEY (ClassID),
  FOREIGN KEY (Inst.ID) REFERENCES INSTRUCTOR(Inst.ID)
);

CREATE TABLE Enroll
(
  StudentID INT NOT NULL,
  ClassID INT NOT NULL,
  PRIMARY KEY (StudentID, ClassID),
  FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID),
  FOREIGN KEY (ClassID) REFERENCES CLASSE(ClassID)
);