CREATE TABLE CHEMIST
(
  EmployeeID INT NOT NULL,
  PRIMARY KEY (EmployeeID)
);

CREATE TABLE PROJECT
(
  ProjectID INT NOT NULL,
  PRIMARY KEY (ProjectID)
);

CREATE TABLE EQUIPMENT
(
  EquipmentID INT NOT NULL,
  EquipmentName INT NOT NULL,
  PRIMARY KEY (EquipmentID)
);

CREATE TABLE ASSIGNMENT
(
  Date INT NOT NULL,
  EmployeeID INT NOT NULL,
  EquipmentID INT NOT NULL,
  ProjectID INT NOT NULL,
  PRIMARY KEY (EmployeeID, EquipmentID, ProjectID),
  FOREIGN KEY (EmployeeID) REFERENCES CHEMIST(EmployeeID),
  FOREIGN KEY (EquipmentID) REFERENCES EQUIPMENT(EquipmentID),
  FOREIGN KEY (ProjectID) REFERENCES PROJECT(ProjectID)
);