CREATE TABLE TROOP
(
  TroopID INT NOT NULL,
  TroopName INT NOT NULL,
  PRIMARY KEY (TroopID)
);

CREATE TABLE LEADER
(
  LeaderID INT NOT NULL,
  LeaderName INT NOT NULL,
  TroopID INT,
  PRIMARY KEY (LeaderID),
  FOREIGN KEY (TroopID) REFERENCES TROOP(TroopID)
);

CREATE TABLE SCOUT
(
  SctID INT NOT NULL,
  SctName INT NOT NULL,
  TroopID INT NOT NULL,
  PRIMARY KEY (SctID),
  FOREIGN KEY (TroopID) REFERENCES TROOP(TroopID)
);

CREATE TABLE CAMPSITE
(
  CampsiteID INT NOT NULL,
  Location INT NOT NULL,
  Campsite.Loc INT NOT NULL,
  PRIMARY KEY (CampsiteID)
);

CREATE TABLE RESERVATION
(
  StartDate INT NOT NULL,
  EndDate INT NOT NULL,
  ReservationID INT NOT NULL,
  SctID INT NOT NULL,
  LeaderID INT NOT NULL,
  CampsiteID INT NOT NULL,
  PRIMARY KEY (SctID, LeaderID, CampsiteID),
  FOREIGN KEY (SctID) REFERENCES SCOUT(SctID),
  FOREIGN KEY (LeaderID) REFERENCES LEADER(LeaderID),
  FOREIGN KEY (CampsiteID) REFERENCES CAMPSITE(CampsiteID)
);