USE LDO;
CREATE TABLE DENTIST
(
  DentistID BIGINT NOT NULL,
  DentistLName VARCHAR(50) NOT NULL,
  DentistFName VARCHAR(50) NOT NULL,
  ContactNo BIGINT NOT NULL,
  EMailID VARCHAR(50) NOT NULL,
  DentistLicenceNo BIGINT NOT NULL,
  Yearof_DDSDMD_Graduation BIGINT NOT NULL,
  Speciality VARCHAR(50) NOT NULL,
  PRIMARY KEY (DentistID),
  UNIQUE (DentistLicenceNo)
);

CREATE TABLE TREATMENT
(
  TreatmentID BIGINT NOT NULL,
  TreatmentType VARCHAR(50) NOT NULL,
  Treatment_Duration BIGINT NOT NULL,
  PRIMARY KEY (TreatmentID)
);


CREATE TABLE SUPPLIER
(
  SupplierID BIGINT NOT NULL,
  SupplierName VARCHAR(50)NOT NULL,
  SupplierAddress VARCHAR(50)NOT NULL,
  Supplier_Contact BIGINT NOT NULL,
  PRIMARY KEY (SupplierID)
);


CREATE TABLE DRUG
(
  DrugID BIGINT NOT NULL,
  DrugName VARCHAR(50) NOT NULL,
  DrugForm VARCHAR(50) NOT NULL,
  DrugType VARCHAR(50) NOT NULL,
  Drug_Status VARCHAR(50) NOT NULL,
  PRIMARY KEY (DrugID)
);


CREATE TABLE HYGIENIST
(
  DentalHygLicenceNo BIGINT NOT NULL,
  HygName VARCHAR(50)  NOT NULL,
  HygID BIGINT NOT NULL,
  Hyg_Contact BIGINT NOT NULL,
  Practice_in_Years BIGINT NOT NULL,
  PRIMARY KEY (HygID),
  UNIQUE (DentalHygLicenceNo)
);

CREATE TABLE INSURANCE
(
  InsuranceID BIGINT NOT NULL,
  Insurance_Company VARCHAR(50) NOT NULL,
  Coverage_Category VARCHAR(50) NOT NULL,
  InsContact BIGINT NOT NULL,
  PRIMARY KEY (InsuranceID)
);

CREATE TABLE STAFF
(
  StaffID BIGINT NOT NULL,
  StaffName VARCHAR(50)  NOT NULL,
  PRIMARY KEY (StaffID)
);


CREATE TABLE Administers
(
  Dosage VARCHAR(50) NOT NULL,
  Time_Administered VARCHAR(50) NOT NULL,
  TreatmentID BIGINT NOT NULL,
  DrugID BIGINT NOT NULL,
  PRIMARY KEY (TreatmentID, DrugID),
  FOREIGN KEY (TreatmentID) REFERENCES TREATMENT(TreatmentID),
  FOREIGN KEY (DrugID) REFERENCES DRUG(DrugID)
);

CREATE TABLE Supplies
(
  BatchID BIGINT NOT NULL,
  Quantity BIGINT NOT NULL,
  ExpiryDate DATE NOT NULL,
  DrugID BIGINT NOT NULL,
  SupplierID BIGINT NOT NULL,
  PRIMARY KEY (BatchID),
  FOREIGN KEY (DrugID) REFERENCES DRUG(DrugID),
  FOREIGN KEY (SupplierID) REFERENCES SUPPLIER(SupplierID),
  UNIQUE (DrugID, SupplierID)
);



CREATE TABLE PATIENT
(
  PatientID BIGINT NOT NULL,
  Contact_No BIGINT NOT NULL,
  PatiendFName VARCHAR(50) NOT NULL,
  PatientLName VARCHAR(50) NOT NULL,
  DoB DATE NOT NULL,
  Allergies VARCHAR(100) NOT NULL,
  Address VARCHAR(100) NOT NULL,
  Gender VARCHAR(50) NOT NULL,
  SSN BIGINT,
  Medical_PreConditions VARCHAR(100) NOT NULL,
  Alternate_Contact BIGINT,
  DentistID BIGINT NOT NULL,
  InsuranceID BIGINT,
  PRIMARY KEY (PatientID),
  FOREIGN KEY (DentistID) REFERENCES DENTIST(DentistID),
  FOREIGN KEY (InsuranceID) REFERENCES INSURANCE(InsuranceID),
  UNIQUE (SSN)
);

CREATE TABLE APPOINTMENT
(
  AppointmentID BIGINT NOT NULL,
  AppointmentDate DATE NOT NULL,
  AppointmentTime VARCHAR(50) NOT NULL,
  Appointment_Reason VARCHAR(50) NOT NULL,
  PatientID BIGINT NOT NULL,
  DentistID BIGINT,
  HygID BIGINT,
  TreatmentID BIGINT NOT NULL,
  StaffID BIGINT NOT NULL,
  PRIMARY KEY (AppointmentID),
  FOREIGN KEY (PatientID) REFERENCES PATIENT(PatientID),
  FOREIGN KEY (DentistID) REFERENCES DENTIST(DentistID),
  FOREIGN KEY (HygID) REFERENCES HYGIENIST(HygID),
  FOREIGN KEY (TreatmentID) REFERENCES TREATMENT(TreatmentID),
  FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID)
);

CREATE TABLE BILL
(
  Bill_No BIGINT NOT NULL,
  AmtInsured BIGINT NOT NULL,
  AmtUnInsured BIGINT NOT NULL,
  Billing_Date DATE NOT NULL,
  Bill_Status VARCHAR(50) NOT NULL,
  StaffID BIGINT NOT NULL,
  PRIMARY KEY (Bill_No),
  FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID)
);

CREATE TABLE PAYMENT
(
  PaymentAmt BIGINT NOT NULL,
  PaymentReciept_No BIGINT NOT NULL,
  PaymentMode VARCHAR(50) NOT NULL,
  PaymentDate DATE NOT NULL,
  InsuranceID BIGINT NOT NULL,
  StaffID BIGINT NOT NULL,
  PatientID BIGINT NOT NULL,
  PRIMARY KEY (PaymentReciept_No),
  FOREIGN KEY (InsuranceID) REFERENCES INSURANCE(InsuranceID),
  FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID),
  FOREIGN KEY (PatientID) REFERENCES PATIENT(PatientID)
);

